### ISSUE TITLE
SBT launcher robocopy on every boot

### ISSUE THREAD

**Issue by melezov** [sbt/sbt-launcher-package#173]
Attached is the output of running SBT with echo set to off.
You can see that robocopy is invoked on every boot, copying preloaded into ~/.sbt everytime.

Running JVM 8u144 on Windows 10

[stdout.txt](https://github.com/sbt/sbt-launcher-package/files/1181428/stdout.txt)

**Comment by tksk** [comment]
sbt.bat is wrong. `_TO_BE_REPLACED`  must be replaced with "0.3.16" before shipping SBT itself.
[https://github.com/sbt/sbt-launcher-package/pull/160#issuecomment-299226125](url)

**Comment by razie** [comment]
just downloaded 0.13.16 on windows and I see the same behaviour.

**Comment by hemant51** [comment]
use robocopy

**Comment by georgeeerenee** [comment]
When I rebooted (http://eed3si9n.com/sbt-server-reboot) the server project, I opted to go with single instance because it simplifies the implementation, and that's what bunch of ppl wanted as well...or it is easy tp swich on other because many time i have issues with robocopy, gs rich copy 360 enterprise work well on every boot.
