### ISSUE TITLE
Insecure instructions for yum and apt repository setup

### ISSUE THREAD

**Issue by koniiiik** [sbt/sbt-launcher-package#94]
I noticed that the setup instructions for the yum repository on bintray simply disable GPG verification. Wouldn't it be better to modify these to enable verification by default?

Also, the setup instructions for the apt repository include the following command:

```
sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 642AC823
```

This is really not that good an idea, since collision attacks on short key IDs are [really easy](https://evil32.com) to pull off these days, which means adding a key to the package manager's trusted keyring only based on the short ID is a security risk. Instead, the instructions should be amended to use the full fingerprint.

**Comment by eed3si9n** [comment]
> I noticed that the setup instructions for the yum repository on bintray simply disable GPG verification. Wouldn't it be better to modify these to enable verification by default?

Could you link to the instruction so we can correct it?

> This is really not that good an idea, since collision attacks on short key IDs are really easy to pull off these days, which means adding a key to the package manager's trusted keyring only based on the short ID is a security risk. Instead, the instructions should be amended to use the full fingerprint.

Thanks for letting us know.

**Comment by koniiiik** [comment]
Oh, sorry. I think this was what I had in mind: http://www.scala-sbt.org/download.html (the linked yum repo definition contains the line `gpgcheck=0`.

**Comment by eed3si9n** [comment]
We followed the official instruction from Bintray, and Bintray happens to be using insecure instruction then. 

```
$ curl https://bintray.com/sbt/rpm/rpm
#bintray--sbt-rpm - packages by  from Bintray
[bintray--sbt-rpm]
name=bintray--sbt-rpm
baseurl=http://dl.bintray.com/sbt/rpm
gpgcheck=0
enabled=1
```

http://blog.packagecloud.io/eng/2014/11/24/howto-gpg-sign-verify-rpm-packages-yum-repositories/

> Unfortunately, signing and verifying RPM packages and yum repositories is tricky and there are a few bugs which can prevent clients from properly verifying signatures.

**Comment by czenker** [comment]
I would like to push this issue again. 

Just stumbled upon it myself and at the current state I would not recommend anyone to include the rpm repo at the current state. (_only_ talking about rpm! - didn't look into deb, but it seems fine).

To point out what the problem here is: When the rpm repo is enabled on a computer, basically everyone on the wire (or able to spoof a DNS record) can modify _all_ packages, because nothing is encrypted or signed. Those packages would be installed as root, allowing to modify the system in every way imaginable with minimal effort.

### So, this is... BAD! What to do about it?

Changing the `baseurl` to HTTPS seems to be a quick win and makes tampering with the data way harder. From my tests Bintray does support it and the repo still works.

`repo_gpgcheck` checks the metadata of the repository. I'm not sure about Bintray, but Artifactory does support signed repo metadata in its module. You would need to have a private key stored on bintray (or trust theirs!?). But I'm not sure about the details.

Lastly using `gpgcheck` might be a viable option if you could manage to sign the rpms. I'm not sure how you build them, but it should be as simple as calling `rpmsign`.

If there is any way I could help to push this issue forward, please let me know.

**Comment by eed3si9n** [comment]
Our current instruction is

```
curl https://bintray.com/sbt/rpm/rpm | sudo tee /etc/yum.repos.d/bintray-sbt-rpm.repo
sudo yum install sbt
```

so we're good now?
